import fib_util

## Problem ##
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

LOOP_LARGE_LIMIT = 100000000000000000

## Solution ##
def solution():
	four_million = 4000000
	sum = 0
	for i in fib_util.fib_gen(LOOP_LARGE_LIMIT):
		if i % 2 == 0:
			sum += i
		if i > four_million:
			return sum

## Execution ##
def main():
	print(solution())

if __name__ == '__main__':
	main()



